const map = {
  'Administrowanie bazami danych (ABD)': 'abd',
  'Algorytmy i Struktury Danych - edux (ASD)': 'asd',
  'Aplikacje Baz Danych (APBD)': 'apbd',
  'Automaty i Gramatyki (AUG)': 'aug',
  'Bezpieczeństwo Systemów Informatycznych (BSI)': 'bsi',
  'Bezpieczeństwo Systemów Informatycznych (ANG) - 2012 (BSI)': 'bsi_ang_2012',
  'Bezpieczeństwo Systemów Informatycznych 2018 (BSI_ANG)': 'bsi_ang_2018',
  'BYT_P (BYT)': 'byt',
  'Edukacja dla bezpieczeństwa (EDB)': 'edb',
  'Fizyka k1 (FIZK1)': 'fizk1',
  'Fizyka k2 (FIZK2)': 'fizk2',
  'Fizyka Kolos1 (angielska) (FIZ)': 'fiz',
  'Grafika Komputerowa (GRK)': 'grk',
  'Hurtownie danych i aplikacje OLAP (HUR)': 'hur',
  'Legal foundations of business (PPB)': 'ppb_ang',
  'Matematyka Dyskretna - edux - 2012 ZIMA (MAD2012A)': 'mad2012a',
  'Matematyka Dyskretna 2020 (MAD)': 'mad',
  'Modelowanie i Analiza Systemów informacyjnych (MAS)': 'mas',
  'Narzędzia Sztucznej Inteligencji (NAI)': 'nai',
  'Prawne Podstawy Działalności Gospodarczej (PPB)': 'ppb',
  'Rachunkowość Podmiotow Gospodarczych (RPG)': 'rpg',
  'RBD egz 2016 zaoczne (RBDz)': 'rbdz',
  'Relacyjne Bazy Danych (RBD)': 'rbd',
  'Sieci Komputerowe - ang - egzamin  (SKJ)': 'skj',
  'Sieci Komputerowe 1 (SKO1/SKJ)': 'sko1-skj',
  'Sieci Komputerowe 2 - edu - 2011 ZIMA (SKO2)': 'sko2',
  'SYSTEM DOSKONALENIA KOMPETENCJI PROGRAMISTYCZNYCH (SDKP)': 'sdkp',
  'Systemy Baz Danych (SBD)': 'sbd',
  'Systemy Baz Danych zima 2015 (SBD2015)': 'sbd2015',
  'Systemy operacyjne (SOP)': 'sop',
  'Technika i Architektura Komputerów (TAK)': 'tak',
  'Technika i Architekture Komputerów (TAK) [ENG] (TAKE)': 'tak_ang',
  'Technologie i Platformy Chmury  Obliczeniowej (TPC)': 'tpc',
  'Technologie Internetu (TIN)': 'tin',
  'Technologie Internetu - 2017 (TIN)': 'tin2017',
  'Wstęp do systemów informacyjnych (WSI)': 'wsi',
  'Zarządzanie projektem informatycznym (ZPR) (ZPR)': 'zpr',
  'ZBD - pytania od studentów (ZBD)': 'zbd',
}

const getId = (subject) => map[subject] || subject.toLowerCase().replace(/ /g, '_').replace(/\//g, '_');

module.exports = { getId };
