const skip = [
  // "1 (1)",
  // "1 (ABD)",
  // "Administrowanie bazami danych (ABD)",
  // "Algorytmy i Struktury Danych - edux (ASD)",
  // "Aplikacje Baz Danych (APBD)",
  // "Automaty i Gramatyki (AUG)",
  // "Bezpieczeństwo Systemów Informatycznych (BSI)",
  // "Bezpieczeństwo Systemów Informatycznych (ANG) - 2012 (BSI)",
  // "Bezpieczeństwo Systemów Informatycznych 2018 (BSI_ANG)",
  // "BYT_P (BYT)",
  // "Edukacja dla bezpieczeństwa (EDB)",
  // "Fizyka k1 (FIZK1)",
  // "Fizyka k2 (FIZK2)",
  // "Fizyka Kolos1 (angielska) (FIZ)",
  // "Grafika Komputerowa (GRK)",
  // "Hurtownie danych i aplikacje OLAP (HUR)",
  // "Legal foundations of business (PPB)",

  "Matematyka Dyskretna - edux - 2012 ZIMA (MAD2012A)",

  // "Matematyka Dyskretna 2020 (MAD)",
  // "Modelowanie i Analiza Systemów informacyjnych (MAS)",
  // "Narzędzia Sztucznej Inteligencji (NAI)",
  // "Prawne Podstawy Działalności Gospodarczej (PPB)",
  // "Rachunkowość Podmiotow Gospodarczych (RPG)",
  // "RBD egz 2016 zaoczne (RBDz)",
  // "Relacyjne Bazy Danych (RBD)",
  // "Sieci Komputerowe - ang - egzamin  (SKJ)",
  // "Sieci Komputerowe 1 (SKO1/SKJ)",
  // "Sieci Komputerowe 2 - edu - 2011 ZIMA (SKO2)",
  // "SYSTEM DOSKONALENIA KOMPETENCJI PROGRAMISTYCZNYCH (SDKP)",
  // "Systemy Baz Danych (SBD)",
  // "Systemy Baz Danych zima 2015 (SBD2015)",
  // "Systemy operacyjne (SOP)",
  // "Technika i Architektura Komputerów (TAK)",
  // "Technika i Architekture Komputerów (TAK) [ENG] (TAKE)",
  // "Technologie i Platformy Chmury  Obliczeniowej (TPC)",
  // "Technologie Internetu (TIN)",
  // "Technologie Internetu - 2017 (TIN)",
  // "Wstęp do systemów informacyjnych (WSI)",
  // "Zarządzanie projektem informatycznym (ZPR) (ZPR)",
  // "ZBD - pytania od studentów (ZBD)"
];

module.exports = { skip };
